set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",*-256color*:Tc"
set -g display-time 3000

set -g mouse on

set -g base-index 1
set -g pane-base-index 1

set -g window-status-format '#I:#W#F'
set -g window-status-current-format ' #I:#W#F '
set -g window-status-current-style bg='#9f0000',fg='#ffffff'

set -g pane-active-border-style fg=blue
set -g pane-border-style fg='#555555'

set -g status-position bottom
set -g status-bg '#151515'
set -g status-fg '#bdbdbd'
set -g status-left '#{?#{==:#{client_key_table},root},,#[fg=#44ff33]tmux }#[fg=#ffe300]#h #[fg=#00c7ff]#{user} #[fg=#ffffff,bg=#383838] #S #[bg=#151515] '
set -g status-left-length 0
set -g status-right '#[fg=#ffe300]%Y-%m-%d#[bg=#151515]#[fg=#02e3ff] %H:%M '
set -g status-right-length 0
set -g status-interval 20
set -g message-style fg=#f6f6f6,bg=#445281,fill=#445281

set -g lock-command vlock

set -g set-titles on
set -g set-titles-string "#T"

unbind -T root -aq
unbind -T prefix -aq
unbind -T tmux -aq
unbind -T copy-mode -aq

set -g prefix None
set -g prefix2 None
set -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection


bind -n M-t set key-table tmux
bind -T tmux M-t set key-table root


bind -T tmux M-1 select-window -t :=1
bind -T tmux M-2 select-window -t :=2
bind -T tmux M-3 select-window -t :=3
bind -T tmux M-4 select-window -t :=4
bind -T tmux M-5 select-window -t :=5
bind -T tmux M-6 select-window -t :=6
bind -T tmux M-7 select-window -t :=7
bind -T tmux M-8 select-window -t :=8
bind -T tmux M-9 select-window -t :=9
bind -T tmux M-0 select-window -t :=10

bind -T tmux M-- next-layout
bind -T tmux M-= previous-layout

bind -T tmux M-w resize-pane -U
bind -T tmux M-a resize-pane -L
bind -T tmux M-s resize-pane -D
bind -T tmux M-d resize-pane -R

bind -T tmux M-W resize-pane -U 5
bind -T tmux M-A resize-pane -L 5
bind -T tmux M-S resize-pane -D 5
bind -T tmux M-D resize-pane -R 5

bind -T tmux M-y select-window -t :^
bind -T tmux M-u previous-window
bind -T tmux M-i next-window
bind -T tmux M-o select-window -t :$

bind -T tmux M-Y swap-window -t :^ \; select-window -t :^
bind -T tmux M-U swap-window -t -1 \; previous-window
bind -T tmux M-I swap-window -t +1 \; next-window
bind -T tmux M-O swap-window -t :$ \; select-window -t :$

bind -T tmux M-h split-window -v -c '#{pane_current_path}'
bind -T tmux M-j select-pane -t +1
bind -T tmux M-k select-pane -t -1
bind -T tmux M-l split-window -h -c '#{pane_current_path}'

bind -T tmux M-H join-pane -h
bind -T tmux M-J swap-pane -D
bind -T tmux M-K swap-pane -U
bind -T tmux M-L join-pane

bind -T tmux M-q copy-mode
bind -T tmux M-e select-layout -E
bind -T tmux M-r command-prompt -p "New window name:" "rename-window '%%'"
bind -T tmux M-p choose-buffer

bind -T tmux M-f join-pane -h
bind -T tmux M-g join-pane

bind -T tmux M-z resize-pane -Z
bind -T tmux M-x set-option status
bind -T tmux M-c {
	clear-history
	display "Scrollback cleared."
}
bind -T tmux M-v move-window
bind -T tmux M-b break-pane
bind -T tmux M-n new-window
bind -T tmux M-N new-session
bind -T tmux M-m select-pane -m

bind -T tmux M-Enter last-window
bind -T tmux M-Space last-pane

bind -T tmux "M-`" {
	source-file ~/.tmux.conf
	display "~/.tmux.conf sourced!"
}

bind -T tmux "M-["  swap-pane -U
bind -T tmux "M-]"  swap-pane -D
bind -T tmux "M-\\" list-keys
bind -T tmux "M-'"  detach
bind -T tmux "M-;"  command-prompt

bind -T tmux M-, choose-tree -Zw
bind -T tmux M-. choose-tree -Z
bind -T tmux M-/ choose-tree -Zs

set -g key-table tmux

if-shell "test -f ~/.tmux.conf.local" "source-file ~/.tmux.conf.local"
